[DEFAULT]
sources = src/infrastructure/persistence/migrations
# В нем прописываем путь до БД с подстановкой данных в формате 'database = postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}'
%include = yoyo-local.ini
batch_mode = on
verbosity = 0
