CREATE TABLE "tasks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "content" text NOT NULL,
  "status_id" integer NOT NULL,
  "deadline_days" integer NOT NULL,
  "create_user_id" integer NOT NULL,
  "executor_user_id" integer,
  "created_at" timestamp DEFAULT (NOW()),
  "updated_at" timestamp DEFAULT (NOW()),
  "deleted_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "surname" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "role" varchar NOT NULL,
  "created_at" timestamp DEFAULT (NOW()),
  "updated_at" timestamp DEFAULT (NOW()),
  "deleted_at" timestamp
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "user_id" integer NOT NULL,
  "task_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (NOW())
);

CREATE TABLE "status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE INDEX ON "tasks" ("status_id");

CREATE INDEX ON "tasks" ("create_user_id");

CREATE INDEX ON "tasks" ("executor_user_id");

CREATE UNIQUE INDEX ON "users" ("email");

CREATE INDEX ON "users" ("username");

CREATE INDEX ON "comments" ("task_id");

CREATE INDEX ON "comments" ("user_id");

COMMENT ON COLUMN "tasks"."created_at" IS 'Автоматически при создании';

COMMENT ON COLUMN "tasks"."updated_at" IS 'Автоматически обновляется при UPDATE';

ALTER TABLE "tasks" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("create_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("executor_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
