-- create 'comments' table.
-- depends: 20260712_03_Dl4Hv-create-tasks-table
CREATE TABLE comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  user_id integer NOT NULL,
  task_id integer NOT NULL,
  created_at timestamp DEFAULT (NOW()),
  updated_at timestamp DEFAULT (NOW()),
  deleted_at timestamp
);

CREATE INDEX ON comments (task_id);
CREATE INDEX ON comments (user_id);

ALTER TABLE comments ADD FOREIGN KEY (user_id) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE comments ADD FOREIGN KEY (task_id) REFERENCES tasks (id) DEFERRABLE INITIALLY IMMEDIATE;

COMMENT ON TABLE comments IS 'Комментарии, прикрепленные к задаче.';
COMMENT ON COLUMN comments.id IS 'ID комментария задачи (Автогенерация).';
COMMENT ON COLUMN comments.content IS 'Тело комментария.';
COMMENT ON COLUMN comments.user_id IS 'ID пользователя, оставившего комментарий (Внешний ключ к таблице users).';
COMMENT ON COLUMN comments.task_id IS 'ID задачи, к которой прикреплен комментарий (Внешний ключ к таблице tasks).';
COMMENT ON COLUMN comments.created_at IS 'Дата создания комментария (Автогенерация).';
COMMENT ON COLUMN comments.updated_at IS 'Дата обновления комментария (Автообновление).';
COMMENT ON COLUMN comments.deleted_at IS 'Дата удаления комментария.';
