-- create 'tasks' table.
-- depends: 20260712_02_IUduf-create-user-table
CREATE TABLE tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  content text NOT NULL,
  status_id integer NOT NULL,
  deadline_days integer NOT NULL,
  create_user_id integer NOT NULL,
  executor_user_id integer,
  created_at timestamp DEFAULT (NOW()),
  updated_at timestamp DEFAULT (NOW()),
  deleted_at timestamp
);

CREATE INDEX ON tasks (status_id);
CREATE INDEX ON tasks (create_user_id);
CREATE INDEX ON tasks (executor_user_id);

ALTER TABLE tasks ADD FOREIGN KEY (status_id) REFERENCES status (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE tasks ADD FOREIGN KEY (create_user_id) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE tasks ADD FOREIGN KEY (executor_user_id) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;


COMMENT ON TABLE tasks IS 'Данные по задаче.';
COMMENT ON COLUMN tasks.id IS 'ID задачи (Автогенерация).';
COMMENT ON COLUMN tasks.name IS 'Название задачи.';
COMMENT ON COLUMN tasks.content IS 'Описание задачи.';
COMMENT ON COLUMN tasks.status_id IS 'ID статуса задачи (Внешний ключ к таблице statuses).';
COMMENT ON COLUMN tasks.deadline_days IS 'Кол-во дней на выполнение задачи.';
COMMENT ON COLUMN tasks.create_user_id IS 'ID пользователя, создавший задачу (Внешний ключ к таблице users).';
COMMENT ON COLUMN tasks.executor_user_id IS 'ID пользователя, выполняющий задачу (Внешний ключ к таблице users).';
COMMENT ON COLUMN tasks.created_at IS 'Дата создания задачи (Автогенерация).';
COMMENT ON COLUMN tasks.updated_at IS 'Дата обновления задачи (Автообновление).';
COMMENT ON COLUMN tasks.deleted_at IS 'Дата удаления задачи.';
