# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-13T07:35:54+00:00

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class CreateTaskData(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    user_id: Annotated[int, Field(examples=[1234])]
    content: Annotated[str, Field(examples=['Description of task'])]
    deadline_days: Annotated[Optional[int], Field(examples=[7], ge=1)] = None


class EditTaskData(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    user_id: Annotated[Optional[int], Field(examples=[1234])] = None
    status_name: Annotated[Optional[str], Field(examples=['in review'])] = None
    deadline_days: Annotated[Optional[int], Field(examples=[7], ge=1)] = None


class AppointmentExecutorTaskData(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    user_id: Annotated[int, Field(examples=[1234])]


class UpdateStatusData(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    user_id: Annotated[int, Field(examples=[1234])]
    status_name: Annotated[str, Field(examples=['in review'])]


class UpdateDeadlineData(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    user_id: Annotated[int, Field(examples=[1234])]
    days: Annotated[int, Field(examples=[7], ge=1)]


class CommentsTaskData(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    user_id: Annotated[int, Field(examples=[1234])]
    content: Annotated[str, Field(examples=['Comment text'])]


class CreateUserData(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    name: Annotated[str, Field(examples=['Ivan Petrov'])]
    email: Annotated[EmailStr, Field(examples=['ivan@example.com'])]


class Task(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    id: Annotated[Optional[int], Field(examples=[1])] = None
    user_id: Annotated[Optional[int], Field(examples=[1234])] = None
    content: Annotated[Optional[str], Field(examples=['Description of task'])] = None
    status_name: Annotated[Optional[str], Field(examples=['in review'])] = None
    deadline_days: Annotated[Optional[int], Field(examples=[7])] = None
    created_at: Annotated[
        Optional[AwareDatetime], Field(examples=['2026-06-05T10:00:00Z'])
    ] = None
    updated_at: Annotated[
        Optional[AwareDatetime], Field(examples=['2026-06-05T10:10:00Z'])
    ] = None


class Comment(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    id: Annotated[Optional[int], Field(examples=[1])] = None
    task_id: Annotated[Optional[int], Field(examples=[1])] = None
    user_id: Annotated[Optional[int], Field(examples=[1234])] = None
    content: Annotated[Optional[str], Field(examples=['Comment text'])] = None
    created_at: Annotated[
        Optional[AwareDatetime], Field(examples=['2026-06-05T10:00:00Z'])
    ] = None


class User(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    id: Annotated[Optional[int], Field(examples=[1])] = None
    name: Annotated[Optional[str], Field(examples=['Ivan Petrov'])] = None
    email: Annotated[Optional[EmailStr], Field(examples=['ivan@example.com'])] = None
    created_at: Annotated[
        Optional[AwareDatetime], Field(examples=['2026-06-05T10:00:00Z'])
    ] = None


class Error(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    code: Annotated[str, Field(examples=['TASK_NOT_FOUND'])]
    message: Annotated[str, Field(examples=['Задача с ID 123 не найдена'])]
